### ISSUE TITLE
fmod extension how to ios, android build

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-FMOD#9]
### Description

fmod extension how to ios, android build
![image](https://github.com/YoYoGames/GMEXT-FMOD/assets/7219276/4d3237ea-b918-4c7f-8c22-41d3b14bc0a0)

![image](https://github.com/YoYoGames/GMEXT-FMOD/assets/7219276/d541d3ae-7cf5-4924-b1c3-c24718d188bc)

### Steps To Reproduce

1. Start GameMaker
2. android, ios build
3. build fail
4. See the issue
![image](https://github.com/YoYoGames/GMEXT-FMOD/assets/7219276/bd685458-b40c-43c6-953a-4038d937d0c6)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Android, iOS

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
hello @searoopy 

Based on our review, it seems you are encountering some issues due to not using the extracted libraries. Instead of using the actual DMG file, you should utilize the extracted version of these libraries. The contents of your iOS/Android SDK folder should include the following:

![image](https://github.com/YoYoGames/GMEXT-FMOD/assets/85873067/d08d9cc3-5a27-4058-ae2b-2143e5b14460)

<br>

> [!TIP]
> You should use your preferred extraction tool (such as 7Zip) to unpack the contents of the `.dmg` (iOS) or `.tar.gz` (Android) files.
